### ISSUE TITLE
Pause the app execution.

### ISSUE THREAD

**Issue by mlopez0** [am15h/object_detection_flutter#14]
Hi, this is not an app issue. But maybe anyone can provide me with some ideas in how to achieve my goal.

I'm using this project as a base for another project I've been working for a couple of months. But I'm still struggling with the Isolate handling. 

The basic idea is to detect and object, then take a "screenshot" and then this image will be compared with predefined set of images. 

For example: The model detect a "ball" the app take a screenshot and then using a comparison algorithm it will return the type of ball (baseball, golf, football). Once the comparison process is completed it will navigate to a "result screen" where the app should display the type of ball found.

I'm facing two problems here.
1. While I'm 'waiting' for the comparison algorithm to complete the object detection is still running in the background and detecting more objects. 

I modified the recognition.dart class and I added a new attribute
```
// Cropped image is where the object detected is located (like a screenshot)
Image cropedImage;
```

Then on my home_view.dart, on the `resultCallback function`

```
  void resultsCallback(List<Recognition> results) {

    setState(() {
      this.results = results;
    });

    if (results.isNotEmpty) {
      comparisonAlgorithm(results);
      });

    }

  comparisonAlgorithm(List<Recognition> results) async {
    setState(() {
      // I want to use this variable to display a loading image or something like that...
      _ComparisonStatus = true;
      _imageFoundStatus = false;
    });

    // Comparison is a custom class where I will store the result of the algorithm comparison.
    Comparison comparison; 
    Map ComparisonResult = {};

//    for (var x = 0; x < results.length; x++) {
    comparison = Comparison(0, results[0].cropedImage);
    // Here the app should await and do not make any object detection until the process has been completed.
    ComparisonResult = await comparison.algorithmGeneration;
//    }

    // One or more images has been found
    if (ssimComparisonResult != null) {
      setState(() {
       // comparison process has been completed, so we don't need to display the "loading" anymore
        _ComparisonStatus = false;
       // boolean used to navigate to the success screen
        _imageFound = true;
      });
    }

    if (_imageFound) {
      _openSuccess();
    }
  }
```

2. When I navigate to the "success" screen the object detection is still running in the background and detecting more objects, I tried to implement the function pause 
```
// File isolate_utils.dart


  void pause() async {
    _isolate.pause();
  }

  static void entryPoint(SendPort sendPort) async {
    final port = ReceivePort();
    sendPort.send(port.sendPort);

    await for (final IsolateData isolateData in port) {
      if (isolateData != null) {
        Classifier classifier = Classifier(
            interpreter:
                Interpreter.fromAddress(isolateData.interpreterAddress),
            labels: isolateData.labels);
        imageLib.Image image =
            ImageUtils.convertCameraImage(isolateData.cameraImage);
        if (Platform.isAndroid) {
          image = imageLib.copyRotate(image, 90);
        }
        Map<String, dynamic> results = classifier.predict(image);
        isolateData.responsePort.send(results);

      }
    }
  }

```

and on the file
//camera_view.dart 
```
      Map<String, dynamic> inferenceResults = await inference(isolateData);

//      isolateUtils.pause();

      var uiThreadInferenceElapsedTime =
          DateTime.now().millisecondsSinceEpoch - uiThreadTimeStart;

      // pass results to HomeView
      widget.resultsCallback(inferenceResults["recognitions"]);

      // pass stats to HomeView
      widget.statsCallback((inferenceResults["stats"] as Stats)
        ..totalElapsedTime = uiThreadInferenceElapsedTime);

      // set predicting to false to allow new frames
      setState(() {
        predicting = false;
        isolateUtils.pause();
      });
    }
  }

```

But I don't know how to resume the Isolate when I click on the button "back" to detect another object, I have to close the app and start the app again in order to make another object detection.

**Comment by am15h** [comment]
> But I don't know how to resume the Isolate when I click on the button "back" to detect another object, I have to close the app and start the app again in order to make another object detection.

Did you try using, https://api.dart.dev/stable/2.12.2/dart-isolate/Isolate/resume.html on pressing back.

**Comment by mlopez0** [comment]
Thanks for the support @am15h , the problem was solved using Provided
