### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildDebug'.

### ISSUE THREAD

**Issue by piggychu0w0** [am15h/object_detection_flutter#19]
I download the project and process it, but it shows wrong message.
`Launching lib\main.dart on sdk gphone x86 in debug mode...
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/tflite_flutter-0.5.0/lib/src/delegates/gpu_delegate.dart:58:10: Error: The getter 'addressOf' isn't defined for the class 'TfLiteGpuDelegateOptionsV2'.
 - 'TfLiteGpuDelegateOptionsV2' is from 'package:tflite_flutter/src/bindings/types.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/tflite_flutter-0.5.0/lib/src/bindings/types.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.

        .addressOf);
         ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/tflite_flutter-0.5.0/lib/src/delegates/metal_delegate.dart:42:70: Error: The getter 'addressOf' isn't defined for the class 'TFLGpuDelegateOptions'.
 - 'TFLGpuDelegateOptions' is from 'package:tflite_flutter/src/bindings/types.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/tflite_flutter-0.5.0/lib/src/bindings/types.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        TFLGpuDelegateOptions.allocate(allowPrecisionLoss, waitType).addressOf);
                                                                     ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf8.dart:63:33: Error: The getter 'addressOf' isn't defined for the class 'Utf8'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf8.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  String toString() => fromUtf8(addressOf);
                                ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+1/lib/src/path_provider_windows_real.dart:126:25: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
          knownFolderID.addressOf, KF_FLAG_DEFAULT, NULL, pathPtrPtr);
                        ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1039:7: Error: The getter 'addressOf' isn't defined for the class 'LOGFONT'.
 - 'LOGFONT' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      addressOf.cast<Uint8>().elementAt(28).cast<Utf16>();
      ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1084:29: Error: The getter 'addressOf' isn't defined for the class 'ENUMLOGFONTEX'.
 - 'ENUMLOGFONTEX' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  LOGFONT get elfLogFont => addressOf.cast<LOGFONT>().ref;
                            ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1086:29: Error: The getter 'addressOf' isn't defined for the class 'ENUMLOGFONTEX'.
 - 'ENUMLOGFONTEX' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  String get elfFullName => addressOf
                            ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1092:26: Error: The getter 'addressOf' isn't defined for the class 'ENUMLOGFONTEX'.
 - 'ENUMLOGFONTEX' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  String get elfStyle => addressOf
                         ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1098:27: Error: The getter 'addressOf' isn't defined for the class 'ENUMLOGFONTEX'.
 - 'ENUMLOGFONTEX' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  String get elfScript => addressOf
                          ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2660:7: Error: The getter 'addressOf' isn't defined for the class 'OSVERSIONINFO'.
 - 'OSVERSIONINFO' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      addressOf.cast<Uint8>().elementAt(20).cast<Utf16>().unpackString(128);
      ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2671:11: Error: The getter 'addressOf' isn't defined for the class 'OSVERSIONINFO'.
 - 'OSVERSIONINFO' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        ..addressOf.cast<Uint8>().elementAt(20).value = 0;
          ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2716:24: Error: The getter 'addressOf' isn't defined for the class 'BLUETOOTH_DEVICE_INFO'.
 - 'BLUETOOTH_DEVICE_INFO' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  String get szName => addressOf
                       ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2809:7: Error: The getter 'addressOf' isn't defined for the class 'BLUETOOTH_PIN_INFO'.
 - 'BLUETOOTH_PIN_INFO' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      addressOf.cast<Uint8>().elementAt(BTH_MAX_PIN_SIZE).value;
      ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2812:5: Error: The getter 'addressOf' isn't defined for the class 'BLUETOOTH_PIN_INFO'.
 - 'BLUETOOTH_PIN_INFO' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    addressOf.cast<Uint8>().elementAt(BTH_MAX_PIN_SIZE).value =
    ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2817:28: Error: The getter 'addressOf' isn't defined for the class 'BLUETOOTH_PIN_INFO'.
 - 'BLUETOOTH_PIN_INFO' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      String.fromCharCodes(addressOf.cast<Uint8>().asTypedList(pinLength));
                           ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2825:7: Error: The getter 'addressOf' isn't defined for the class 'BLUETOOTH_PIN_INFO'.
 - 'BLUETOOTH_PIN_INFO' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      addressOf.cast<Uint8>().elementAt(idx).value = pinData[idx];
      ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart:38:31: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  final iid = GUID.allocate().addressOf;
                              ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart:56:33: Error: The getter 'addressOf' isn't defined for the class 'GUID'.

 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.

  final clsid = GUID.allocate().addressOf;
                                ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/winrt/winrt_helpers.dart:86:40: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.

  final riidCalendar = GUID.allocate().addressOf;
                                       ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IDesktopWallpaper.dart:197:38: Error: The getter 'addressOf' isn't defined for the class 'COMObject'.
 - 'COMObject' is from 'package:win32/src/com/combase.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    final ptr = COMObject.allocate().addressOf;
                                     ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IDesktopWallpaper.dart:200:49: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(CLSID_DesktopWallpaper).addressOf,
                                                ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IDesktopWallpaper.dart:203:48: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(IID_IDesktopWallpaper).addressOf,
                                               ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IFileOpenDialog.dart:58:38: Error: The getter 'addressOf' isn't defined for the class 'COMObject'.
 - 'COMObject' is from 'package:win32/src/com/combase.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    final ptr = COMObject.allocate().addressOf;
                                     ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IFileOpenDialog.dart:61:47: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(CLSID_FileOpenDialog).addressOf,
                                              ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IFileOpenDialog.dart:64:46: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(IID_IFileOpenDialog).addressOf,
                                             ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IFileSaveDialog.dart:99:38: Error: The getter 'addressOf' isn't defined for the class 'COMObject'.
 - 'COMObject' is from 'package:win32/src/com/combase.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.

    final ptr = COMObject.allocate().addressOf;
                                     ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IFileSaveDialog.dart:102:47: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.

        GUID.fromString(CLSID_FileSaveDialog).addressOf,
                                              ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IFileSaveDialog.dart:105:46: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(IID_IFileSaveDialog).addressOf,
                                             ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IKnownFolderManager.dart:164:38: Error: The getter 'addressOf' isn't defined for the class 'COMObject'.
 - 'COMObject' is from 'package:win32/src/com/combase.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    final ptr = COMObject.allocate().addressOf;
                                     ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IKnownFolderManager.dart:167:51: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(CLSID_KnownFolderManager).addressOf,
                                                  ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IKnownFolderManager.dart:170:50: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(IID_IKnownFolderManager).addressOf,
                                                 ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/INetworkListManager.dart:128:38: Error: The getter 'addressOf' isn't defined for the class 'COMObject'.
 - 'COMObject' is from 'package:win32/src/com/combase.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    final ptr = COMObject.allocate().addressOf;
                                     ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/INetworkListManager.dart:131:51: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(CLSID_NetworkListManager).addressOf,
                                                  ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/INetworkListManager.dart:134:50: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
        GUID.fromString(IID_INetworkListManager).addressOf,
                                                 ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IWbemLocator.dart:82:38: Error: The getter 'addressOf' isn't defined for the class 'COMObject'.
 - 'COMObject' is from 'package:win32/src/com/combase.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/com/combase.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.

    final ptr = COMObject.allocate().addressOf;
                                     ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IWbemLocator.dart:84:68: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    final hr = CoCreateInstance(GUID.fromString(CLSID_WbemLocator).addressOf,
                                                                   ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IWbemLocator.dart:85:64: Error: The getter 'addressOf' isn't defined for the class 'GUID'.

 - 'GUID' is from 'package:win32/src/structs.dart' ('/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.

        nullptr, CLSCTX_ALL, GUID.fromString(IID_IWbemLocator).addressOf, ptr);
                                                               ^^^^^^^^^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/tflite_flutter-0.5.0/lib/src/bindings/types.dart:6:7: Error: Struct 'TfLiteInterpreter' is empty. Empty structs are undefined behavior.
class TfLiteInterpreter extends Struct {}
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/tflite_flutter-0.5.0/lib/src/bindings/types.dart:9:7: Error: Struct 'TfLiteInterpreterOptions' is empty. Empty structs are undefined behavior.
class TfLiteInterpreterOptions extends Struct {}
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/tflite_flutter-0.5.0/lib/src/bindings/types.dart:12:7: Error: Struct 'TfLiteModel' is empty. Empty structs are undefined behavior.
class TfLiteModel extends Struct {}
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/tflite_flutter-0.5.0/lib/src/bindings/types.dart:15:7: Error: Struct 'TfLiteTensor' is empty. Empty structs are undefined behavior.
class TfLiteTensor extends Struct {}
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/tflite_flutter-0.5.0/lib/src/bindings/types.dart:18:7: Error: Struct 'TfLiteDelegate' is empty. Empty structs are undefined behavior.
class TfLiteDelegate extends Struct {}
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf8.dart:23:7: Error: Struct 'Utf8' is empty. Empty structs are undefined behavior.
class Utf8 extends Struct {
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf16.dart:16:7: Error: Struct 'Utf16' is empty. Empty structs are undefined behavior.
class Utf16 extends Struct {
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1083:7: Error: Struct 'ENUMLOGFONTEX' is empty. Empty structs are undefined behavior.
class ENUMLOGFONTEX extends Struct {
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2807:7: Error: Struct 'BLUETOOTH_PIN_INFO' is empty. Empty structs are undefined behavior.
class BLUETOOTH_PIN_INFO extends Struct {
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2932:7: Error: Struct 'EXCEPINFO' is empty. Empty structs are undefined behavior.
class EXCEPINFO extends Struct {}
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2938:7: Error: Struct 'PROPERTYKEY' is empty. Empty structs are undefined behavior.
class PROPERTYKEY extends Struct {}
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2945:7: Error: Struct 'PROPVARIANT' is empty. Empty structs are undefined behavior.
class PROPVARIANT extends Struct {}
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2950:7: Error: Struct 'SAFEARRAY' is empty. Empty structs are undefined behavior.
class SAFEARRAY extends Struct {}
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2957:7: Error: Struct 'CLSID' is empty. Empty structs are undefined behavior.
class CLSID extends Struct {}
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2964:7: Error: Struct 'STATSTG' is empty. Empty structs are undefined behavior.
class STATSTG extends Struct {}
      ^
/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2971:7: Error: Struct 'NLM_SIMULATED_PROFILE_INFO' is empty. Empty structs are undefined behavior.
class NLM_SIMULATED_PROFILE_INFO extends Struct {}
      ^

/C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/allocation.dart:47:33: Error: Expected type 'T' to be a valid and instantiated subtype of 'NativeType'.
  final int totalSize = count * sizeOf<T>();
                                ^

FAILURE: Build failed with an exception.

* Where:
Script 'D:\winnie\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\winnie\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 3m 9s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
`
I had tried the way in [here](https://stackoverflow.com/questions/61930007/how-to-solve-execution-failed-for-task-appcompileflutterbuilddebug) and [here](https://stackoverflow.com/questions/67651806/error-the-getter-addressof-isnt-defined-for-the-class-utf8). But it doesn't work, is there any suggestion for me to solve the problem?

Thanks a lot for help!!

**Comment by undcloud** [comment]
I meet the same issue, how to solve it ?
