### ISSUE TITLE
Work with Yolov4-tiny.tflite

### ISSUE THREAD

**Issue by piggychu0w0** [am15h/object_detection_flutter#20]
I gonna to do a project with yolov4-tiny, I just put my file on but it's not work.
Is there any thing i need to modify?
And this is the first problem as I put my file in the project. Is there any way to solve it?

`RangeError (RangeError (index): Invalid value: Not in inclusive range 0..1: 2)`

Thanks a lot for help!!

**Comment by rj76** [comment]
Did you manage to fix this? Since you closed the ticket...
