### ISSUE TITLE
Object detection with specific image

### ISSUE THREAD

**Issue by piggychu0w0** [am15h/object_detection_flutter#22]
I have seen that it wrote "If you need to test a specific image, you can get a file path where you can put the image. Look at getExternalStorageDirectory() from path_provider package;". 

I'm new in flutter, so it quite difficult for me to know how to revise it. Does anyone know it? Or where is the part that I need to revise?

I will be very grateful for your help.

**Comment by tsathya98** [comment]
+1

I am new to flutter as well. If anyone knows the approach, can you please share it here?
