### ISSUE TITLE
IndexError (RangeError (index): Index out of range: index should be less than 76800: 21)

### ISSUE THREAD

**Issue by jpfcabral** [am15h/object_detection_flutter#26]
Actually i dont know what's happening,  the variable index, in line 45 of image_utils.dart, increase and stop inference.

Flutter Version: 2.5.1
Pixel 5 android-x86 emulator

**Comment by WillianSalceda** [comment]
Boa tarde @jpfcabral. Isso é um problema direto com o Flutter. Caso altere sua versão para a mais recente na branch master, o erro será corrigido. Acredito que deva demorar alguns meses ainda até que essa correção apareça na versão estável do Flutter.

Não posso garantir, mas talvez em outras branches também já esteja corrigido (como na dev, por exemplo).


This is a problem with Flutter. If you change your version to the latest version in the master branch, the bug will be fixed. I believe it may take a few months until this fix appears in the stable version of Flutter.

I cannot guarantee it, but maybe in other branches it is already fixed (like in dev, for example).

**Comment by jpfcabral** [comment]
Obrigado @WillianSalceda . 
Utilizando o Flutter 2.6.0 - 11.0.pre o problema foi resolvido!
